import 'package:flutter/material.dart';
import 'package:flutter_flip_card/flutter_flip_card.dart';
import 'dart:math';

class MemoramaScreen extends StatefulWidget {
  const MemoramaScreen({Key? key}) : super(key: key);

  @override
  State<MemoramaScreen> createState() => _MemoramaScreenState();
}

class _MemoramaScreenState extends State<MemoramaScreen> with TickerProviderStateMixin {
  TextEditingController controller = TextEditingController();
  TextEditingController controller2 = TextEditingController();

  bool show = false;
    late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 1),
    vsync: this,
  )..repeat(reverse: true);

  String texto = 'Flip';
  int contador = 0;
  int contadorArr = 0;
  bool btn = true;
  List<String> englishStr = 
["fetch",
"runt",
"sway",
"fleas",
"bust",
"liable",
"involvement ",
"choke",
"drown",
"quite so",
"tear",
"it's not a big deal",
"it's not use",
"that doesn't work",
"hill",
"steep",
"roll",
"roll up",
"smooth",
"unless",
"through",
"figure out",
"ever ",
"most",
"caveats",
"Retrieve",
"usages",
"embrace",
"dare",
"tight",
"remain ",
"pontoon",
"porpoise",
"poke",
"straight ",
"straight ahead",
"playful",
"chucked ",
"motto",
"sort of",
"sort",
"tough",
"tender",
"besides",
"lingering ",
"fizzled, fizzle",
"what a relief",
"wreak",
"peeking , peek",
"cheats",
"slipped up",
"at ease",
"sunk",
"tan",
"clumsy",
"rehearsal ",
"thrust",
"threat",
"dire",
"harmless",
"mankind",
"otherwise",
"ill",
"floods",
"bending (bend, bent)",
"thus, therefore",
"host",
"devour ",
"flesh",
"distress",
"evolve",
"withstand ",
"slightly ",
"slight",
"light ",
"mutates",
"gene",
"burrowing",
"poisoned ",
"unify",
"spread",
"treatments ",
"gonna",
"eggshells ",
"shell",
"inside out",
"been over",
"whatcha got",
"y'all",
"lotta (lot of)",
"nods",
"due end",
"spring",
"given ",
"deaf ",
"raisin",
"get Right ",
"get",
"lame",
"borrowed ",
"pop it in ",
"riveting ",
"swinging ",
"stepped in",
"show up",
"bail ",
"bail me out",
"get me out",
"get out",
"madhouse ",
"goddammit ",
"further",
"law enforcement ",
"nowhere",
"ankle ",
"injury ",
"slurred speech ",
"slurred ",
"speech",
"falling out",
"tickle ",
"sweeping ",
"needle",
"sewer",
"guilty",
"empowered ",
"you're short five",
"supposedly",
"bullets",
"the more",
"depot",
"shift",
"shitheaped",
"jumpy and tired",
"ripping you off, ripping off",
"mortgage",
"blasting music",
"how about",
"what else",
"fucked you up",
"cut off",
"care",
"your fucking guys",
"pretty much",
"surrounding ",
"surrounded",
"firefly",
"hold out",
"supposed ",
"granddaughter ",
"God bless him",
"long",
"raiders",
"slavers",
"I got jumped",
"outbreak ",
"argue",
"lockup",
"march",
"hunt ",
"hold back",
"throughout ",
"meaningless",
"blowing up",
"guarding , guard",
"dictatorship",
"freedom ",
"all over",
"gather",
"jaw",
"fucker",
"unlock me",
"recall",
"dump me",
"what I'm about to tell you",
"assure",
"reframed",
"how far up",
"how far",
"this far",
"gunpowder ",
"greedy",
"screwed, screwed us over",
"screw",
"shitty ",
"smuggle",
"repurposed",
"we hand",
"jeopardize ",
"stock up",
"bigwig",
"buffer zone",
"follow",
"follow my lead",
"shitting me",
"get on",
"blessed",
"catch up",
"copycat ",
"misjudged",
"the screwup",
"committed ",
"would",
"draw",
"substrate ",
"drive",
"swarmed",
"warm up",
"steady",
"turn",
"turn up",
"into",
"spot",
"tear out",
"heal",
"broken",
"hairline",
"sneak",
"notice",
"worth",
"boarded up",
"twitches ",
"somehow",
"sealed off",
"seal",
"ever",
"I snuck in",
"snuck out",
"explode",
"even",
"stairwell ",
"gross ",
"check it out",
"climbing ",
"floor",
"mess",
"shelter ",
"wires",
"stretching",
"step",
"ripped apart",
"ripped",
"bone",
"rip",
"rip up",
"ground rules",
"ground",
"spare",
"crawled",
"thriving ",
"crane",
"supplied ",
"investors ",
"milestones",
"settled ",
"upper left",
"Forward ",
"jury's still out",
"run out ",
"take your bandage off",
"take off",
"take",
"take up",
"get off me",
"blame ",
"hike",
"lame",
"seeing as",
"hang back a minute",
"grab",
"stashed",
"swallows",
"barfs out",
"zeroing in on ",
"picked over",
"getting funnier",
"useless",
"get shoved",
"shoved ",
"shove",
"bucks",
"grim",
"all at once",
"get bit",
"certain ",
"brands ",
"tainted",
"shelves",
"axe murderer ",
"countyside",
"towns",
"bruise",
"nightfall",
"out loud",
"bum",
"staring at",
"stride ",
"abide",
"wounds",
"unseen",
"whore",
"look like",
"sound like",
"lawnmower",
"management",
"trip",
"aside",
"to get by",
"spool",
"stray",
"seeds",
"stay up",
"made up",
"crush ",
"whomever",
"figure",
"sight",
"sigh",
"still ",
"heading out",
"head",
"wherever",
"bring up",
"dented ",
"swollen",
"breaks down",
"over time",
"wandering ",
"envelope",
"stationary",
"intended",
"pun",
"pun intended ",
"mermaid",
"bra",
"algae ",
"Wonder",
"wondered off",
"dawn",
"plows",
"such",
"scattered ",
"get rid",
"fuss",
"stuck",
"forsake",
"fate",
"plaything",
"vow",
"hound",
"bay",
"age",
"face",
"that",
"scarecrow",
"award",
"outstanding",
"theirs",
"odds",
"settlement",
"ship off",
"bother",
"that's about it",
"stay put",
"around",
"get around",
"jog",
"I'm all turned around",
"squeeze through ",
"hopefully ",
"wronged",
"rat",
"deliver",
"surrender",
"betray",
"hole up",
"discreet",
"trial",
"own",
"tie",
"whatever",
"brought, bring",
"way outta ",
"tight",
"either",
"rape",
"torture",
"come",
"embankment",
"head down",
"get bad",
"dicey",
"pessimist",
"issues",
"endure",
"keep it down",
"pop back",
"selfish ",
"left of",
"as long as",
"make",
"fond farewells",
"fond",
"farewells ",
"involves",
"approach",
"approached",
"rely",
"knock",
"never mind her",
"mind",
"got close",
"all of a sudden",
"set up ",
"raise",
"rub(bed)",
"reckon",
"mumble",
"pass out",
"passing through",
"i just did",
"track",
"guts",
"guts out ",
"proper",
"scare off ",
"handful",
"cells into",
"come into",
"hell up",
"hell",
"back then",
"pocket",
"raiding party",
"raid",
"scope",
"advertising ",
"worship",
"multifaith",
"faith",
"faithful",
"dam",
"sewage",
"plumbing ",
"water heaters",
"council",
"elected",
"pitch",
"pitch in",
"patrols",
"prep ",
"repairs ",
"harvesting ",
"greenhouses",
"livestock ",
"ownership ",
"communism",
"commune",
"newest",
"pet",
"untouched",
"hog",
"goodness ",
"payment",
"week's ride",
"ditch",
"aware",
"protective ",
"folks",
"eggplant ",
"rag",
"trim",
"concern",
"hell of",
"whole lot",
"therein",
"I don't even",
"from the beginning ",
"dying wish ",
"I would have",
"as far as",
"think of anything",
"lately ",
"fail",
"took off",
"took up",
"make up",
"lousy",
"tactful ",
" I stood up",
"right off",
"miss",
"counting on  it",
"borrow",
"wide rigt",
"flinching ",
"cartridge ",
"eject",
"squeeze ",
"fourth down ",
"turnover ",
"just as much",
"Fair enough ",
"lead",
"infirmary",
"stitches",
"grunt",
"tread",
"pride",
"starve",
"sneaking up",
"stab",
"drills ",
"hanging (out)",
"self-preservation",
"mess",
"trickles",
"rusty",
"freedom",
"stealthy ",
"chick",
"avoid ",
"kind of",
"stubborn ",
"as much as",
"slimy",
"wired",
"expose",
"turns out ",
"grid ",
"block",
"trip",
"loot",
"shovel",
"strike",
"oversell",
"saucers",
"useless",
"flawless ",
"lay it on me",
"alligator ",
"vest",
"post",
"painless ",
"behold ",
"Tabernacle ",
"sorrow",
"former",
"bury",
"two at best",
"deer",
"doubt",
"whoever",
"ditto",
"syringe ",
"harm ",
"rely",
"cult",
"preach(er)",
"flock",
"scavenge",
"god's will ",
"cage",
"proven",
"kneecap",
"resort",
"stick ",
"struggle ",
"beyond",
"shepherd",
"equal",
"cunt",
"sleeve ",
"delayed",
"nurse",
"smashed",
"blast",
"rubble",
"cut through",
"skyscraper",
"heals ",
"scratch ",
"debt",
"owe",
"torn apart",
"climber",
"scamper",
"prey",
"primeval",
"forest",
"constrictor",
"ponder",
"whether",
"masterpiece",
"grown-ups",
"since",
"lay",
"aside",
"give up",
"disheartened",
"failure",
"devote",
"instead",
"tiresome",
"glance",
"encounters",
"matter",
"deal",
"close at hand",
"improve",
"whenever",
"neckties",
"greatly",
"please",
"clear-sighted",
"keep",
"meet",
"attemp",
"scarcely",
"i set myself",
"shipwrecked",
"shipwrecked sailor",
"raft",
"amazement",
"amaze",
"sunrise",
"sunset",
"Wake",
"Awake",
"Awaken",
"Arouse",
"odd",
"strange",
"i jumped to my feet",
"thunderstruck",
"blink",
"wink",
"seriousness",
"portrait",
"discourage ",
"courage",
"astonishment",
"fairly",
"stared",
"stared at",
"starting",
"straying",
"uncertainly",
"nor ",
"neither",
"either ",
"faint",
"and yet",
"rather",
"serve",
"binding ",
"dispatch",
"handed off",
"overpowering",
"disobey",
"chap",
"crossly",
"astound",
"fellow",
"greet",
"cumbersome",
"indulgently",
"ram",
"horns",
"apart",
"toss",
"tossed off",
"acquaintance",
"as well as",
"outward ",
"pitch",
"overall",
"grasp",
"closure",
"strength",
"strong",
"stateless",
"type-hint ",
"despondent",
"both",
"at last",
"explanation",
"drop",
"chance",
"little by little ",
"so far",
"cry out",
"cry",
"lovely",
"peal",
"misfortunes ",
"gleam",
"abruptly",
"demand",
"sink",
"reverie",
"last",
"lasted",
"bury",
"half-confidence",
"effort",
"subject ",
"that is so",
"queer",
"post",
"shocked",
"offer",
"wander",
"wander off",
"earnestly",
"perhaps",
"hint",
"string",
"rosy",
"geranium",
"dove",
"shrug",
"forbearance ",
"fashion",
"suffer",
"grief",
"hurt",
"but",
"paint",
"fumble",
"resemblance ",
"seem",
"fair-to-middling ",
"alas",
"grow old",
"departure",
"seized",
"bush",
"herd",
"wise",
"indeed",
"desire",
"sprig",
"upward",
"toward",
"sprout ",
"radish",
"setting down",
"begin--timmidly ",
"first--to",
"rose-bush",
"very first",
"soil ",
"rid",
"bore",
"resemble",
"ought ",
"putting off",
"neglect",
"watch out",
"plainly",
"reserve ",
"skirt",
"beyond",
"force",
"inspire",
"quiet",
"pleasure",
"fond",
"twilight",
"right from noon",
"burden",
"bears",
"meant",
"fool",
"hall",
"threaten",
"right away",
"anyone",
"goof off",
"monks",
"noon",
"once",
"midget ",
"rough",
"prevail",
"Manning ",
"duty",
"came",
"otter",
"paddle",
"sulk",
"glowy",
"behind",
"beams",
"glinmer",
"banish ",
"hopes up",
"rightful",
"heir",
"upon",
"marched",
"laid waste",
"plung",
"fall",
"drag",
"omens",
"prove",
"worthy",
"set out",
"afterwards ",
"ruthless",
"ultimate",
"as much as",
"behalf",
"cove",
"guts",
"overpower",
"braces ",
"drills ",
"reinforce",
"sloppiness ",
"belief",
"look Forward",
"meantime ",
"soothing",
"swift",
"current",
"draft",
"draft off",
"step ",
"misplace",
"keep in mind",
"unceasing ",
"dustbin ",
"fierce",
"shrine",
"thimble ",
"hub",
"vicinity ",
"sacred",
"ravage",
"firecracker",
"weed",
"tight",
"cave in",
"lead up",
"thorn",
"bolt",
"breakfown",
"become",
"spite",
"in spite",
"resentfulness",
"flashed back",
"flash",
"naive",
"reassure ",
"disturb",
"bend down",
"relentlessly",
"went on ",
"breeze",
"figures",
"add up",
"swell up",
"swell",
"pride",
"rage",
"warfare",
"blossom",
"sob",
"comfort",
"rock",
"muzzle ",
"rail",
"awkward",
"blund",
"overtake",
"remind",
"remember ",
"uphold",
"grill",
"room",
"fade away",
"fade",
"come up",
"shrub",
"bud",
"at once",
"chamber",
"rumple (rumpled)",
"poppies",
"coquettish ",
"adornment",
"painstaking",
"yawn",
"beg",
"disarrange ",
"disappoint",
"restrain",
"modest",
"kindness ",
"abash",
"ashamed",
"sprinkle",
"atend",
"vanity",
"glass",
"verge",
"untruth",
"cough",
"wrong",
"in order",
"order",
"remorse ",
"sticky",
"anchor",
"manners",
"avoid ",
"gather",
"sighting",
"parallel",
"though",
"quite",
"affairs",
"outsider",
"stake ",
"at stake",
"wiped out",
"wipe",
"migthy",
"merciless ",
"warn",
"pull back",
"nifty",
"channel",
"upon one",
"fur",
"forthcoming ",
"misunderstanding ",
"tempt",
"dismiss",
"witnessed",
"development ",
"brinery",
"will",
"pleasure",
"take pleasure",
"tend",
"tenderness ",
"tender",
"pity",
"confidence",
"judge",
"deed",
"cast",
"stratagem",
"confide",
"lay behind ",
"lay",
"guess",
"affection",
"carelessly",
"dejection",
"pull up",
"task",
"forgiveness",
"forgive",
"reproach",
"absence",
"bewilder",
"arrested",
"sweetness ",
"while",
"hanging around",
"so far",
"foolish",
"caterpillars",
"acquainted",
"far away",
"claws",
"linger",
"clad",
"royal",
"ermine",
"consumingly",
"cram",
"robe",
"forbid",
"thoroughly",
"fright",
"frightful",
"sputter",
"sputtered",
"vexed",
"vex",
"inquiry",
"fold",
"mantle",
"rule",
"sire",
"hasten",
"marvel",
"forsake",
"pluck",
"carry",
"carry out",
"rest",
"shall",
"command",
"bulky",
"regret",
"carriage",
"wisdom",
"pardon",
"condemn",
"thrift",
"grieve",
"prompt",
"hesitate",
"ambassador",
"hastily",
"conceited",
"admirer",
"salute",
"clap",
"afar",
"acclaim",
"praise",
"regard",
"tippler",
"whom",
"lugubrious",
"so",
"confess",
"bring",
"puzzle",
"arrival",
"amouse",
"balderdash",
"giddy",
"goodness ",
"mistake",
"addition",
"rheumatism",
"loaf",
"businessman ",
"glitter",
"idle",
"set",
"accurate",
"nevertheless",
"retort",
"peevishly",
"cranky",
"silk",
"drawer",
"altogether",
"street lamp",
"lamplighter",
"respect",
"respectfully",
"mop",
"forehead",
"handkerchief",
"square",
"put it out",
"merely",
"farther",
"despise",
"scorn",
"blest",
"pant",
"geographer",
"state",
"scholar",
"stately",
"disaster",
"so would",
"furnish",
"stir",
"excitement",
"sharpen",
"sharpener",
"ink",
"expectant",
"which",
"old-fashioned",
"ephemeral",
"disappearance",
"slight",
"alight"];


 List<String> spanishStr = 
  [
 
"ir a buscar, extraer a, traer a, ir por",
"enano",
"balanceo, sacude ",
"pulgas",
"la quiebra, quebrar",
"responsable, propenso, sujeto",
"intervencion",
"ahogo, la estrangulacion",
"ahogar, ahogarse",
"Asi es ( expresión )",
"la lagrima, el rasgon, rasgar, desgarre",
"no es gran cosa",
"no es util, no sirve",
"no funciona",
"colina",
"empinada",
"rodar",
"enrollar, subirse,arremangar",
"liso",
"a menos que",
"mediante, atraves de, de paso",
"averiguar, descifrar",
"alguna vez, siempre, nunca, una vez (aunque se usa para enfatizar la incredubilidad y sorpresa en una oracion) ",
"la mayoría, más, mucho",
"advertencias",
"recuperar",
"usos",
"abrazar,adoptar.  ",
"atreverse, reto",
"fuerte, apretado, pretar",
"permanecer, mantener ",
"flotador, pontón, pantalán.",
"marzopa, delfin, vaquita marina",
"toque, empujar, meter",
"derecho, recto, hacia, directamente ",
"hacia adelante, todo recto",
"juguetón, divertido, travieso, alegre",
"aventé , arrojé ",
"eslogan",
"parece que, algo asi, de alguna manera, tipo de , Maso menos, aproximadamente ",
"ordenar, especie, ordenar, clase, resolver, solucionar, apartar",
"duro",
"tierno, sensible, suave , oferta, concurso",
"además, por otra parte",
"persistencia, prolongado ",
"fracasado, apagar, fiasco",
"que alivió ",
"hacer, provocar, infligir ",
"espies , espiando, mirar, mirando",
"trucos, engaña, tramposo",
"metió la pata, cometio un error , equivocaste, ha resbalado",
"descansar, a gusto, comodo, a sus anchas ",
"irremplazable , hundido, caido",
"bronceado, moreno ",
"torpe, patoso, tosco, burdo",
"ensayo , repetición, simulacro ",
"el empuje, la estocada, el avance",
"amenaza, peligro, riesgo",
"graves, extremos, extremo",
"inofensivo, inocuo",
"humanidad, ser humano, raza humana",
"de otro modo, de lo contrario ",
"enfermar",
"inunda",
"doblado, flexión",
"así, por lo tanto ",
"anfitrion, hosting; alojamiento, hospedaje",
"devorar ",
"pulpa, carne, piel, descarnar",
"angustia, apuros",
"desarrollarse, evolucionar ",
"soportar, aguantar, resistir",
"ligeramente, un poco, levemente, apenas, un tanto, un poquito, mínimamente, sutilmente",
"ligero, leve, pequeño, minimo, despreciar",
"luz, claro, iluminación, iluminar, encender",
"muta",
"gen, genética ",
"excavar, cavar, madriguera",
"envenenado, intoxicado, contaminado",
"unify",
"extender, difundir, propague",
"tratamientos",
"going to",
"cascada de huevo",
"caparazon, bombardear",
"al reves ",
"revisado, repasado, pasado más ",
"que tienes",
"todos ustedes",
"mucho",
"guiños, gestos, nominaciones",
"pendiente",
"resorte, primavera ",
"dados",
"sordo",
"pasas (fruta)",
"hacerlo bien",
"recibes, entender, poner, lleves",
"patético ",
"prestado",
"ponlo en ",
"fascinante, apasionante",
"balanceando ",
"intervine, metido",
"aparecieron",
"fianza, rescatar",
"pagar la fianza, sacarme ( de la cárcel)",
" sácame ",
"salir ",
"manicomio, loquero, casa de locos",
"maldita sea, carajo, mierda",
"más, además , más lejos",
"orden publico, aplicación de la orden, fuerzas de orden",
"ningún lugar, nada, en ninguna parte",
"tobillo",
"lesion, herid@",
"dificultad para hablar",
"pastoso, confusa, arrastrado, mal articulado ",
"voz, discurso, habla, expresión, intervencion, lenguaje, charla",
"pelea, disputa, desacuerdo",
"cosquillar, cosquillear, hacer cosquillas ",
"barrido (sweep)",
"aguja, punción, jeringa",
"alcantarilla, desagüe ",
"culpable, culposo",
"facultado, empoderado",
"te faltan cinco",
"supuestamente, teóricamente ",
"proyectiles, balas",
"cuánto más, tanto más.",
"almacén, depósito ",
"turno, cambia, cambios",
"mierda, cagado",
"nervioso  y cansado",
"estafandote, estafando",
"hipoteca",
"música a todo volumen",
"por que, que tal ",
"que mas",
"te jodieron",
"cortalo",
"importar,cuidar,cuidado, atención, asistencia",
"tus putos chicos",
"casi, prácticamente,más o menos, bastante",
"alrededor, entorno, ambiente",
"rodear, envolver, circundar,cercar, enmarcar , copar, ceñir ",
"luciernaga",
"resistir, aguantar, retener, tender, sujetar",
"se supone, ",
"nieta",
"dios lo bendiga ",
"mucho tiempo, largo",
"invasores, asaltantes ",
"esclavistas",
"me asaltaron ",
"estallido, epidemia, brote, comienzo",
"discutir, argumentar ",
"encerrado , prisión ",
"marcha, manifestación,desfilar, marchar, manifestarse ",
"cazar, nusqueda",
"contuve, contener",
"a lo largo, en todas partes, en todo, durante todo",
"sin sentido, insignificante , inútil absurdo",
"volando, hacer explotar ",
"vigilando, guardia ",
"dictadura ",
"libertad, liberación ",
"por todo, encima, por doquier",
"reunir, recopilar,recoger, reunirse",
"mandíbula, quijada",
"hijo de puta",
"liberame",
"recordar, recuperar, recuerdo, (memoria)",
"dejarme, abandonarme ",
"lo que te voy a contar",
"asegurar, garantizar",
"redefinido, replanteado ",
"hasta dónde llega,hasta dónde vamos",
"hasta dónde, cuánto, hasta qué punto",
"hasta aquí, muy lejos",
"pólvora ",
"codicioso, avaricioso, ambicioso",
"arruinado, nos jodio",
"tornillo, rosca, atornillar, enroscar, atornillarse",
"de mierda, mal, horrible, jodido",
"traficar",
"reutilizado,reconvertido",
"entregamos",
"poner en peligro, comprometer",
"abastecerse,almacenar,aprovisionarse,surtir",
"pez gordo",
"zona de amortiguación ",
"deducir, seguir, cumplir, respetar. acompañar, perseguir, atender, comprender",
"sigues mi ejemplo",
"tomándo el pelo, bromeando, jodiendome, coña ",
"coger, obtener en, subirse ",
"bendecido",
"alcanzar, recuperar, ponerse al dia",
"imitador",
"juzgado mal",
"el error",
"cometido, comprometido, dedicado, empeñado, confiado",
"sería, habría, gustaría, tendría, estaría, haría, podría",
"sacar, dibujar, empate, llamar",
"sustrato",
"coche, unidad, disco, conducir, impulsar, manejar, llevar",
"rodeado",
"calentar, caliente, calienta, calientan, calentará, calentarte, calienten, calentarnos, calentando, calentarme, calientes, calientas, calentarán, calentamos, caliento, calentaré",
"constante, estable, firme, calmar, estabilizar",
"convertir, turno, apagar, giro, vuelta ",
"aparecer, subir, encender, aumentar, llegar, presentarse, venir, girar",
"en, a, al",
"lugar, punto, sitio, manchar, detectar, observar, contado, reflector",
"arranca",
"sacanar, curar",
"fractura, roto, quebrado",
"fisura (en vez de fractura una fisura) y/o rayita",
"colar, colarse, escabullir",
"aviso, notar, notificacion",
"valer la pena, merecer, valor, valía, mérito, digno",
"tapiado",
"espasmos, tics ",
"de alguna manera, de algún modo",
"sellado ",
"cerrar, sellado",
"nunca",
"me cole, me escabullí",
"escapado",
"explotan",
"incluso, aún, siquiera ",
"escalera ",
"asqueroso ",
"hechar un vistazo ",
"escalar ",
"piso",
"desordenado, lio,",
"refugio, albergue",
"cables, alambres, hilos",
"estirar, se extiende, estiramiento",
"paso",
"destrozado.",
"musculoso, desgarrado",
"hueso",
"arrancar, rasgar, copiar, extraer, romper, ripear, desgarrar",
"hacer pedazos",
"reglas de juego, normas básicas, reglas básicas",
"castigado, basado, fundamentado",
"respuesto, libre; disponible, escatimar;ahorrar",
"metido, arrastrado (arrastrar sin ed), rastreado, rastreo, se arrastro, se metio",
"prospero",
"grua",
"proporcionar, suministro ",
"inversores",
"hitos, logros, metas, etapas, objetivos",
"establecido, asentado",
"parte superior izquierda ",
"hacia adelante, adelante ",
"el jurado aún está deliberand; aún no se ha llegado a una decision ",
"se acaba (run out of; quedarse sin )",
"quítate el vendaje ",
"quitar, llevar",
"sacar, coger, dar, tomarse",
"ocupar, asumir, tomar, abordar",
"quítate de mi",
"reprochar, culpar, culpa, responsable ",
"caminata ",
"patético, tonto, estupido",
"ya que, dado que, viendo que",
"espera un minuto",
"agarrar , tomar",
"escondido, alcamcenado,ocultado ",
"golondrinas, se traga, tragar",
"vomita",
"concentrandose en, concentrándome en",
"saqueado,seleccionado sobre",
"cada vez más gracioso",
"inútil ",
"ser empujado, meterse",
"empujado",
"empujar, meter, poner",
"dólares, pavos, billetes",
"sombrío, triste, lúgubre, siniestro ",
"al mismo tiempo, a la vez",
"ser mordido",
"determinado, ciertos",
"marcas",
"corrompido, contaminado ",
"anaqueles, estantes, estanterías ",
"asesino en serie, asesino del hacha",
"campo",
"ciudades, localidades, pueblos",
"moretón ",
"anochecer ",
"en voz alta ",
"vago, vagabundo, inútil, quemar",
"Mirando fijamente",
"calma, caminar, dar zancadas",
"cumplir, permanecer, soportar",
"heridas, llagas, herida, lesiones",
"invisibles, oculto, no visto",
"prostituto, puto",
"parecer, parecer a",
"suena a",
"cortacesped",
"administración, gestión ",
"trampa, viaje, excursión ",
"a un lado, aparte, al margen",
"para sobrevivir, para salir adelante ",
"carrete, bobina ",
"callejero, extraviado, perdido",
"semillas",
"quedar despierto, quedarse hasta",
"constituido, inventado, maquillado, conformado",
"triturar, machacar ",
"cualquier persona",
"imagino, supongo, pienso",
"espectáculo, vista, ver; avistar, divisar ,a la vista",
"suspiro, suspirar",
"aún asi, todavía,",
"yendo, saliendo, dirigiendo ",
"dirigir, ir, partir ",
"dónde quiera que, sea cuál sea ",
"abrir, traer, mencionar, criar, plantear, sacar, educar, subir, traer a colación, sacar a relucir, sacar adelante, poner ",
"abollado, mellado",
"hinchado, inflamado",
"se descompone ",
"con el tiempo, con el paso del tiempo",
"ambulante, deambulante, vagabundeo",
"envolvente, sobre, envoltura",
"estacionario, fijo, inmóvil",
"destinado, previsto, prometida",
"juego de palabras, chiste, broma, alburear",
"juego de palabras, nunca mejor dicho,  valga la redundancia",
"sirena, Sirenita",
"sujetador",
"algas",
"preguntar, preguntarse, pensar, maravilloso,sorprendente, maravilla ",
"maravilllado",
"amanecer,madrugada",
"arados, quitanieves,arado",
"tal, dicho, semejante, tan, tanto, así, ese",
"disperso, esparcido",
"deshacerse",
"alboroto, escándalo, quejarse, preocuparse",
"atrapado, atascado, pegado, atorado",
"abandonado, desamparar",
"destino",
"juguete",
"voto, promesa, prometer, votar",
"sabueso, perro, acosar, perseguir",
"bahía, laurel, bayo, aullar",
"edad, envejecer ",
"cara, afrontar, enfrentar, facial",
"que, ese, aquel, ello, cual, tan, ahí, para que",
"espantapajaro",
"premio",
"pendiente, excepcional",
"el suyo, la suya, suyo, suyos",
"probabilidades, dificultades, puntos de ventaja",
"solución, asentamiento",
"enviar",
" molestarse",
"eso es todo, eso es, esto es todo",
"quédate ahí ",
"alrededor de, alrededor, por aquí, por ahí ",
"evadir, recorrer, esquivar, saltarse",
"correr, trotar, trote",
"Estoy completamente volteado",
"escurrirse por, meterse por",
"con suerte, ojalá, afortunadamente, esperanzadamente, con esperanza",
"agraviado",
"delatar, rata",
"entregar, ofrecer, proporcionar, brindar, cumplir ",
"rendir, rendirse, entregar",
"traicionar, delatar, traicionarse, revelar , engañar ",
"ocultarse",
"discreción",
"juzgado, judicial, probar",
"poseer, tener, propio, mismo",
"atar, corbata",
"lo que sea",
"traer",
"forma de salir de, salida",
"ajustada, apretado, estrecho",
"ya sea, o , tampoco, cualquiera, ninguno, alguno",
"violar",
"tortura",
"venir, llenar",
"embarcadero",
"cabeza abajo, dirigirse, bajar",
"empeorar",
"arriesgado",
"pesimista",
"cuestiones, problemas, temas",
"soportar, aguantar, resistir, perdurar, sufrir, resistir, durar, perseverar",
"habla más bajo",
"aparecen de nuevo",
"egoísta, egocéntrico ,interesado",
"quedaba de ",
"mientras",
"hacer, realizar, tomar",
"calurosa despedida",
"cariñoso, aprecio, encariñarse",
"despedida , adiós ",
"conlleva, involucra ",
"enfoques, planteamiento, acerca,  estrategias, aproximaciones, criterios, métodos",
"abordado, contactado, enfocado, se acerco, se acercaban, se acercaron, acerqué a, aborda, acercado a, abordar, contactó",
"confiar, depender, basar, basarse, contar, apoyarse, invocar, descansar ",
"golpear, llamar, tocar",
"no le haga caso",
"mente, cabeza, opinión, idea, ánimo, espíritu, parecer, pensamiento, importar, molestar, pensar, recordar, mental, mentalidad, juicio, memoria, cerebro, loco, inteligencia, cuidar",
"se acercaron",
"de repente, de golpe",
"establecer, configurar, crear",
"aumentar, elevar, levantar, plantear, recaudar, criar, subir, crear, dar, alzar, incrementar, mejorar, reunir, obtener, conseguir, suscitar, despertar, juntar, presentar, resucitar, captar, sacar, poner, izar, levantarse ",
"frotar, restregar, masajear",
"creer, suponer, calcular, considerar, reconocer, contar, opinar, estimar",
"murmurar, balbucear, decir entre dientes, susurrar",
"desmayar, desmayarse, repartir, pasar, perder el conocimiento",
"atrevesando",
"lo acabo de hacer",
"pista, canciones, temas, huellas",
"agallas",
"tripas, entrañas, primera papilla",
"adecuada, apropiado, correcto",
"ahuyentar",
"puñado (handful of = puñado de )",
"celulas en, celdas a, celdas dentro",
"entrar en, venir a, entrar a, llegar a",
"maldita boca, pico, maldita vez, hocico",
"infierno, diablo, demonio, follón, mierda, carajo, coño, joder, cojones, puta ",
"ese entonces, aquel entonces, aquella epoca , antes",
"bolsas",
"grupo de ataque/asalto",
"saquear, atacar, asaltar, redada, incursión ",
"alcance, ambito, margen",
"publicidad,propaganda, publicitario",
"culto",
"multirreligioso",
"fe, confianza, religión, creencia, credo",
"fiel, digno de confianza, dedicado",
"presa,represar,hidroeléctrico",
"alcantarillado",
"fontanería ",
"calentadores de agua",
"ayuntamiento, consejo, municipal ",
"electivo, elegido, electo, nombrado, optado",
"lanzar, echar , proponer , campo",
"lanzar en, colaborar, ayudar, arrimar, echar una mano",
"patrullas, patrullajes, rondas",
"preparar",
"reparaciones, reparación, arreglos",
"cosecha, recolección",
"invernaderos, vivero",
"ganado, ganadería, ganadero, animal, pecuario, agropecuario ",
"propiedad, titularidad, propiedad, implicación ",
"comunismo, comunista",
"comunidad, comuna, municipio ",
"más reciente , último, más nuevo ",
"mascota, acariciar, favorito; preferido ",
"intacto",
"cerdos",
"bondad , amabilidad ",
"pago, remuneración ",
"semana de viajé ",
"deshacer, abondonar",
"consciente, al tanto",
"protector, cauteloso ",
"gente , familia ",
"berenjena ",
"trapo",
"recortar, ajustar, cortar",
"preocupación, inquietud, interés, preocupar",
"increíble, excelente, genial",
"lote completo, porción completa, buena cantidad",
"allí, en ello, en esto, en eso, allí dentro, del mismo",
"ni siquiera",
"desde el principio ",
"último deseo, última voluntad ",
"yo hubiera ",
"por lo que, en cuanto a, hasta, hasta donde, en cuanto al, tanto como",
"pensar en nada",
"últimamente, recientemente, hace poco, en los últimos tiempos ",
"fallar, fracasar, dejar",
"despegar",
"tomo, asumió, tomaron, ocupó ",
"conformar, componer, constituir, formar, compensar, representar, integrar, hacer",
"pésimo, malo, mal, asqueroso , horrible, piojoso",
"discreto, prudente",
"me pare (me levanté)",
"justo al lado, enseguida, inmediatamente,justo a la salida",
"perder, extrañar, perderse ",
"cuento con ello, cuenta con eso",
"pedir prestado, prestar, pedir",
"desviado a la derecha",
"estremeciendo ",
"cartucho,casquillo",
"expulsar",
"apretar",
"cuarta oportunidad ",
"facturación, rotación ",
"apenas tanto",
"bastante justo, muy bien, está bien, me parece bien",
"conducir, llevar, liderar, plomo, ventaja, líder, principal, protagonista",
"enfermería ",
"puntadas",
"gruñido, soldado",
"banda de rodamiento ",
"orgullo, soberbia ",
"morir de hambre, privando ",
"sigilosamente ",
"apuñalada ",
"ejercicios, simulacros, taladro",
"pasar el rato",
"autoconservacion",
"ensuciarte,  desorden, andar con",
"goteos",
"oxidado",
"libertad ",
"cauteloso ",
"polluelo, mujer , chavala",
"evitando, eludiendo ",
"algo, un poco, bastante, algo asi, algo asi como, mas o menos",
"terco, obstinado, cabezon",
"tanto como, hasta, por mucho que, cuánto, por más que, aunque, igual que",
"viscoso, baboso, pegajoso",
"cableado, por cable, conectado",
"expuesto, descubierto, visto",
"resulto, resultado",
"red, rejilla",
"al bloque, cuadra, manzana",
"tropezar, viajar, volar, viaje, excursión, paseo",
"saqueo",
"pala, excavadora, palear, apalear ",
"huelga, ataque, golpear, atacar, lograr",
"exagerar,alabar en exceso,sobrevalorar",
"platillos, ovnis",
"inútil,inservible",
"impecable, perfecto, sin defectos",
"echarme la culpa ",
"cocodrilo ",
"chaleco ",
"publicar, poner, enviar, publicación, correo, entrada",
"indoloro ",
"mirad",
"tabernaculo",
"pena",
"pasadas, anteriores , primeras ",
"enterrar, sepultar, esconder",
"dos como mucho ",
"venado, ciervo",
"duda, incertidumbre, dudar, dudarse",
"quién, quienquiera que, cualquiera que, sea quien sea",
"lo mismo",
"jeringa ",
"daño, prejuicio, dañar, perjudicar",
"confiar, depender, basar, basarse, contar, recurrir",
"culto, secta",
"predicar, anunciar, pregonar, sermonear",
"rebaño, acudir en masa",
"recoger, carroñar, escarbar",
"voluntad de Dios",
"jaula, cajón, armazon",
"probado, comprobado ",
"rodilla",
"estación ",
"palo, pegar, adherir, meter, quedarse",
"luchar , lucha",
"más allá,fuera de,además de, de más allá",
"pastor, pastorear",
"igualdad, igualar ",
"coño, puta , perra",
"manga",
"retrasado, retardado, tardío, demorado",
"enfermer@, amamantar,",
"aplastar, exitazo, choque",
"explosión , explotar",
"escombro , ruinas",
"atravesar, penetrar, acabar con",
"rascacielo",
"cura, sana, se cure, cicatrice",
"rasguño, rascar, improvizado",
"deuda",
"deber, adeudar, deberse, tener deudas ",
"desgarrado",
"escalador",
"corretear , escabullirse",
"presa (para comer)",
"primitivo, primaveral",
"bosque",
"constrictora",
"relexionar",
"si, ya sea",
"obra maestra",
"mayores, adultos",
"desde, desde que, ya que",
"poner ",
"al lado, aparte",
"rendir",
"desanimado",
"fracaso",
"dedicar",
"en cambio, en su lugar, sino",
"tedioso, agotador, pesado",
"mirada",
"encuentros",
"importante, asunto, cuestión ",
"trato, cantidad",
"a mano, cerca, al alcance de la mano",
"mejorarse, perfeccionar, aumentar",
"siempre que, cada vez que",
"corbatas",
"enormemente",
"por favor, porfa, complacer, agradar, querer, satisfacer",
"clarividente",
"mantener, guardar,  seguir ",
"reunir, conocer",
"intentar",
"apenas, escasamente, difícilmente, casi no, prácticamente, con dificultad",
"me propuse",
"náufrago, naufragado",
"náufrago",
"balsa, serie",
"asombro, sorpresa, asombrado",
"sorprender, asombrar, maravillar, impresionar, deslumbrar, epatar",
"amanecer",
"atardecer",
"despertar, despertarse, estela, paso, velatorio",
"despierto, consciente, levantado, despejado, despertar, despertarse",
"despertar ,despertarse, suscitar, avivar, alertar, abrir los ojos, darse cuenta, despertador",
"despertado, suscitado, despierta, provocado, levantado, generado",
"extraño, raro, impar",
"extraño, raro",
"salte sobre mis pies",
"atónito, estupefacto, pasmado",
"parpadear",
"guiñar",
"gravedad, seriedad",
"retrato",
"desalentar, disuadir, disuadir, oponerse a",
"valor, coraje, valentía, ánimo, valiente",
"asombro, espanto, escándalo",
"equitativamente, bastante, justamente",
"miró, miraba, miraban",
"miró fijamente, contempló, se quedó mirando",
"partir, partida, empezando",
"alejarse, apartarse, desviarse, vagando ",
"inciertamente, incertidumbre, sin importancia",
"ni, tampoco",
"ni, no, ninguno",
"ya sea, o, tampoco",
"débil, desmayar, tenue",
"y sin embargo, y aún así",
"mejor dicho, más bien, bastante",
"servir",
"vinculante, unión, obligatorio, enlace",
"envio, despacho, expedicion, enviar, despachar, expedir",
"traspasar, entregada, transferida, encargarse, deshacen de ",
"abrumadora, abrumador",
"desobedecer",
"cap, muchacho",
"con mal humor",
"asombrar, sorprender, pasmar",
"compañero, colega, tio, compatriota",
"saludar",
"engorroso, complicado, incomodo",
"indulgentemente",
"ovejo, carnero",
"cuernos, astas, trompetas, bocinas, trompas",
"aparte, abajo, lejos, independientemente, separadamente, en pedazos, a un lado",
"mezclar, tirar, lanzar, resolver, echar, arrojar, agregar, sortear",
"descarté",
"conocido, conocimiento, conocida, relacion, amistad",
"asi como, ademas de",
"externo",
"proponer",
"en general, general, en todo, sobre todo, en su totalidad",
"comprender",
"cierre, finalizar, fin, conclusión, clausura",
"fuerza, resistencia, fortaleza",
"fuerte, solido, firme",
"apátrida, desnacionalizado, sin estado, apatridia, sin patria",
"declaración de tipo",
"abatido, desanimado",
"tanto, ambos, los dos",
"por fin, al fin",
"explicación, aclaración, interpretación",
"caída, gota, descanso, soltar, dejar, caer",
"oportunidad, posibilidad, posible, probabilidad, casual, arriesgarse, arriesgar",
"poco a poco, de a poco ",
"hasta ahora, hasta el momento",
"clamar, gritar, llorar, exclamar, lanzar un grito",
"llorar, aclamar, gritar, llamar, grito, clamor ",
"encantador",
"repique",
"desgracias, infortunios, desventuras, desdichas",
"brillar, resplandecer, relucir, destello, resplandor, rayo",
"abruptamente ,bruscamente, repentinamente",
"demanda, exigencia, petición, exigir, demandar, pedir",
"fregadero, hundir, fregador",
"ensueño, ensoñación, sueño, ensimismamiento, meditación, fantasia",
"último, pasado, anterior, apellido, última vez",
"durado, perdurado, prolongado, aguantado",
"enterrar, sepultar, esconder, sepultura ",
"confianza a medias",
"esfuerzo, iniciativa, intento, trabajo, empeño, labor, pena, afán ",
"tema, sujeto, asunto, temática, someter, someterse",
"esto es así, que es tan, eso es tan",
"marica, raro, extraño, gay, maricon, homosexual ",
"poste, puesto, publicación, postal, posterior, vacante, publicar, poner",
"sorprendido, conmocionado, emocionado, impactado, impresionado",
"oferta, ofrecer, brindar",
"pasear, vagar, deambular, recorrer",
"deambular, perderse, desviarse",
"sinceramente, seriamente, fervientemente, encarecidamente ",
"quizas",
"toque",
"cadena, cuerda, serie,  encordar, ensartar",
"rosado",
"flor de color rosa",
"paloma",
"encoger, encoger los hombros",
"tolerancia, paciencia",
"moda, de moda, crear, diseñar",
"sufrir, parecer, tener, experimentar, soportar, resentirse ",
"dolor, pena, duelo",
"dolor",
"sino, sin embargo, no obstante, solo, menos, excepto, salvo, solo, solamente, sino que",
"pintura, pintar, dibujar, pintarse",
"hacer algo con torpeza, hurgar, dejar caer, titubear",
"parecido, semejanza, similitud, semejante",
"parece",
"justo a medio",
"por desgracia, ay, desgraciadamente, lamentablemente, desafortunadamente",
"envejecer",
"salida, partida, marcha",
"incautado, confiscado,",
"arbusto",
"rebaño ",
"sabio",
"en efecto, en efecto, efectivamente, ciertamente",
"deseo",
"puntilla, ramita",
"hacia arriba, ascendente, al alza, alcista, creciente, subida, ascendiente, ascensional",
"hacia, para, con, para con, pos, con respecto a",
"brote",
"rabano",
"dejar, lugar, poniendo, instalación ",
"principiante ",
"novato",
"rosal",
"primero, primerísimo ",
"suelo, tierra, ensuciar, manchar",
"eliminar, librado",
"agujero, perforación, orificio, perforar, taladrar, aburrir, aburrido, latoso",
"parecer",
"debería, debe",
"posponiendo",
"negligencia, descuidar",
"cuidado",
"claramente ",
"reserva",
"bordear",
"más allá, fuera de, de más allá",
"forzar",
"inspirar",
"tranquila",
"placer",
"aficionado, aprecio , encariñarse ",
"crepúsculo, ocaso, atardecer, crepuscular",
"desde el medio día",
"carga",
"lleva, osos",
"destinado, significado ",
"tonto, engañar",
"salón ",
"amenazar, poner en peligro",
"inmediatamente, enseguida ",
"cualquiera",
"holgazanear, perder tiempo",
"monjes",
"medio dia",
"una vez, después, en cuanto, antes, tras, antaño, tan pronto, antiguamente ",
"enano, diminuto",
"difícil",
"prevalecer, predominar, imperar, oponerse, reinar, imponer, triunfar",
"defendiendo",
"deber, derecho, obligación, servicio, impuesto, trabajo, tarea, guardia",
"vino, llegó, vinieron",
"nutria, lobito",
"paleta, remar, palear, chapotear",
"estar enfurruñado, enfurruñarse, estar enfadado, enfado, malhumor ",
"brillante, radiante, luminosa",
"detras",
"vigas, rayos",
"rayos , destello ",
"desterrar, eliminar, expulsar",
"esperanzas, ilusiones ",
"legitimo, justo, verdadero",
"hereder@, sucesor",
"sobre, con, después, por, para, segun, luego, encima",
"marcharon",
"arrasaron",
"sumergir, immersion",
"caída, caer, decreciente",
"arrastrar, resistencia ",
"presagios, augurios",
"demostrar, probar, resultar ",
"digno, merecedor, valioso ",
"establecido, enunciado, fijado, recogido, exponer, disponer, partir, salir",
"posteriormente , después, luego, más adelante ",
"despiadado, impecable, cruel",
"supremo",
"tanto como, hasta, por mucho que",
"nombre , favor, parte, cuenta",
"cala, ensenada, caleta, bahía ",
"agallas",
"dominar, vencer, abrumar, sobrepasar",
"corsé, soporte, rodillera, prepararse, preparar, apuntalar",
"taladro, perforación, broca, perforar, taladrar, sondear ",
"reforzar, fortalecer",
"descuido, dejadez, desaliño",
"creencia, convicción, fe",
"estoy ansioso, espero, deseando",
"mientras tanto, entre tanto",
"camante, relajante, suave",
"rápida ",
"corriente, curso, actualidad",
"borrador, anteproyecto, redactar, elaborar, preparar, preliminar, provisional ",
"sacar ",
"paso, etapa, media, entrar, pisar, pasar",
"extraviar, perder, traspapelar, descolocar",
"tener en cuenta, tener presente, tener en mente, tomar en cuenta ",
"incesante ",
"cubo de basura, basurero",
"feroz, fiero, fuerte, duro, ferozmente ",
"santuario ",
"dedal, tambor, cartucho",
"centro, eje, concentrador",
"inmediaciones, alrededor, priximidad, vecindad",
"sagrada",
"devastar, asolar, arrasar , estrago",
"petardo",
"hierba",
"apretado",
"ceder, derrumbarse , derrumbar ",
"conducen, suben",
"espina, aguijón, espino, espinoso, piedra, molestia",
"perno, tornillo, rayo, atornillar, huir, empernar",
"desglose, avería, ruptura",
"convertir en, convertirse en, volver, volverse, hacerse, hacer, llegar a ser, quedar, quedarse, resultar, adquirir",
"pesar, rencor, rabia, despachar, fastidiar, herir",
"a pesar ",
"resentimiento",
"escena retrospectiva",
"flash, destellar, parpadear, repentina",
"ingenuas, inocentes, simple",
"tranquilizar, tranquilizar a, asegurar, asegurar a, convencer a, tranquilizarse, reafirmar a",
"molestar, pruebas, alterar, interrumpir, disturbar, afectar, inquietar ",
"agacharse, inclinarse, inclina, agachándose",
"sin descanso, implacablemente, incansablemente, incansablemente, incesamente",
"continuo, prosiguió, siguió",
"brisa, viento, suspiro, pasar fácilmente",
"cifras",
"'sum' se refiere al resultado final de la adición, mientras que 'add up' se refiere al proceso de llevar a cabo la adición o suma de varios números o cantidades para obtener ese resultado final.",
"hincharse, hinchar",
"hincharse, inflamarse, hinchar, oleaje, ola, hinchazón, estupendo",
"orgullo, soberbia, manada, enorgullecer, enorgullecerse, estar orgulloso",
"rabia, ira, furia, rabiar, enfurecerse, rugir",
"guerra, guerrilla, combate, guerrear",
"florecer, briar, desarrollarse, for, floración, florecimiento",
"sollozar, llorar, sollozo, llanto",
"comodidad, consolar, conformar, aliviado, cómodo",
"piedra, rocoso, rupestre, rockero, rockear, sacudir, mecer, peñon",
"hocico, bozal, boca, amordazar, silenciar, callar",
"ferroviario, trem, ferrocarril, Férreo, clamar, maldecir, viajar por carril, carril, riel, ferroviaria, barandilla",
"incómodo, torpe, raro, vergonzoso, incomodidad, comprometido",
"error, equivocación, error garrafal, meter la pata, cometer un error",
"adelantar, superar, alcanzar, adelantamiento",
"recordar, recordarse, hacer acordar, recomendar",
"recordar",
"defender, mantener, respetar, sostener,cumplir, confirmar, garantizar, apoyar",
"parrilla, asar",
"habitación, sala, salón, cuarto, espacio, comedor, ambiente, lugar",
"desvanecerse, desaparecieron",
"desvanecerse, desaparecer, desvanecer, descolorarse, difuminar, marchitarse, difuminarse, atenuar",
"venir, subir, surgir, llegado",
"arbusto, matorral, seto, mata",
"brote, amigo, cogollo, brotar, retoñar, florecer",
"a la vez, al mismo tiempo, de inmediato, de una vez, inmediatamente, enseguida, en seguida, de golpe",
"Cámara, sala, cuarto, habitación, recámara",
"arrugar, despeinar, desarreglar",
"amapola,",
"coqueto, coquetona ",
"adorno, ornamento, ornato, decoración",
"minucioso, laborioso, meticuloso, esmerado, arduo, cuidadoso",
"bostezar, abrirse, bostezo",
"rogar, suplicar , pedir, mendigar, implorar, pedir limosna, limosnear",
"desajustar, desarreglar, descasar",
"decepcionar, defraudar, desilusionar",
"restringir, contener, limpiar, frenar, refrescarse, contenerse, impedir, sujetar",
"modesto, moderado, sencillo, humilde ",
"amabilidad, bondad, gentileza",
"avergonzar, confundir, abochornar ",
"avergonzado, apenado, vergonzoso, abochornado, vergüenza",
"espolvorear, rociar, esparcir, pizca, rociada, salpicadura",
"atender, tender, cuidar, ocuparse, propender, curar",
"vanidad, vanidoso",
"vidrio, de cristal ",
"borde, límite, umbral, filo, margen",
"falsedad, mentira, falso",
"tos, toser, escupir",
"mal, equivocado, malo, error, injusticia, crimen, equivocadamente",
"para, por orden, en orden, en regla, ordenado, con el fin, y asi",
"orden, pedido, encargo, manera, pedir, ordenar, solicitar, comprar",
"remordimiento, arrepentimiento,",
"pegajoso",
"ancla, anclar ",
"modales, maneras, comportamientos ",
"evitar",
"reunir, recopilar, recoger, reunirse, juntar, recabar",
"avistamiento",
"paralelo, paralelismo, paralela, simultáneo, análogo, en paralelo, paralelamente, simultáneamente, línea paralela, comparar, igualar",
"aunque, sin embargo, si bien, aun así, no obstante ",
"bastante",
"asuntos, cosas",
"extraño, forastero",
"participación, estaba, apuesta, apostar, estacar , arriesgar",
"en juego, en riesgo, en peligro, en cuestión",
"eliminado, aniquilado",
"limpiar, toallita ",
"poderoso",
"despiadado, implacable",
"advertir, avisar, alertar, prevenir",
"retirar, retroceder, tirar hacia atras",
"ingenioso, elegante, estupendo ",
"canal, canalizar",
"a uno, sobre uno",
"peluche, peludo",
"próximo,futuro, siguiente ",
"malentendido",
"tentar, seducir",
"descartar,despedir, rechazar",
"testigo, presenciar, testimoniar, ser testigo, testimonial ",
"desarrollo, elaboración, evolución, fomento, creación, formulación , promoción, urbanizacion",
"soborno, corrupción, antisoborno,",
"voluntad, testamento, albedrío , querer, desear, legal, ordenar, anhelar",
"placer, gusto, satisfacción, complacer, gustar, dar gusto, agrado, alegría",
"disfrutar, complacer, gozar, deleitarse",
"atender, tender, cuidarse, ocuparse, proponer, curar",
"ternura, sensibilidad, dolor, cariño, dulzura, palpación, suavidad, terneza",
"licitación, oferta, concurso, tierno, sensible, suave, licitar, ofertar",
"lástima, pena, piedad, compadecer, tener lástima",
"confianza, seguridad, confidencialidad, confidencia",
"juez, juzgar",
"escritura, transferir, ceder",
"fundir, lanzar, elenco",
"artimañas, estratagemas, formacion",
"confiar, confiarse",
"habia detras",
"poner,sentar,colocar, laico, laical, lego, disposición, polvo, secular, dejar, yacia, ponen",
"suponer, adivinar, creer, suposición, conjetura, estimación",
"afecto, cariño, afección ",
"descuidadamente, sin cuidado, negligentemente, por descuido, despreocupadamente",
"abatamiento, desaliento, desanimo, depresión ",
"levantar, sacar, subir, subirse, obtener, llegar, detenerse, arrancar, extraer",
"tarea, trabajo, labor, deber, encargar",
"piedad",
"perdonar",
"reproche, reprochar ",
"ausencia, inasistencia, falta",
"desconcertar, aturdir, confundir, dejar perpleo",
"arresto, atención, paro, captura, arrestar, detener, parar, frenar, prender, prisión, contra",
"dulzura, dulzor, dulce, suavidad",
"mientras que, rato",
"por aqui, por alli, por ahí,dando vueltas",
"hasta ahora",
"tonto, insensato estupido",
"orugas",
"conocer, familiarizado, conoce",
"lejos",
"garras",
"permanecer, quedarse, persistir, perdurar, quedar, detenerse, durar, descansar, demorar",
"revestido, vestido, revestimiento",
"realeza, real, regio, mayestático, espléndido",
"armiño",
"consumiendo ",
"meter, abarrotar, empollar, preparación intensiva ",
"manta, tunica, manto, vestir",
"prohibir, impedir ",
"fondo, completamente, bien",
"miedo, susto, asustar",
"espantoso, terrible, aterrador",
"chisporrotear, farfullar, petardear",
"pulverizado, farfullado, balbucear",
"molesto, controvertido, irritado, enfadado, enojado, vejado, desconcertado, fastidiado, polémico, confuso, discutido, debatido",
"irritar, fastidiar, afligir, vejar, disgustar, disgustarse",
"investigacion, consulta, indagacion, pregunta, solicitud",
"doblar, plegar, retirarse, plegarse, incorporar, pliegue, doblez, redil, plegado, rebaño, plegable",
"manto, capa, cubrir",
"gobernar, regla",
"señor, padre, engendrar ",
"acelerar, apresurar, apresurarse, adelantar, precipitar",
"maravillar, maravillarse, maravilla, prodigio, asombro",
"abandonar, dejar, renegar de, renunciar de",
"arrancar, desplumar, depilar, valor, agallas, coraje",
"llevar, transportar, cargar, portar, seguir, tener, conllevar, continuar, acarreo, alcanzar",
"llevar a cabo, realizar, efectuar, cumplir, desempeñar, desarrollar, ejecutar, llevar adelante, cometer, poner en práctica, perpetrar, practicar, realizarse, sacar adelante, consumar, verificar, cumplimentar",
"resto, descanso ,reposo, restante ,paz, descansar, reposar, apoyar, quedar, apoyarse, demás, tranquilidad, resta, apoyo, respiro, pausa, soporte, basarse, silencio, permanecer, quietud , posarse, depender, reclinar, posar",
"deber, podrá, hará, podrán, voy",
"comando, mando, orden, mandato, mandamiento, dominio, ordenar, mandar, comandar, dirigir, dominar, exigir, comandancia, comandante, instrucción, jefatura, tener, disponer, imponer, ganarse, capitanear, encomienda, acaudillar, disponer de",
"voluminoso, abultado, pesado, grueso, aparatoso, corpulento",
"lamentar, arrepentir, arrepentirse, sentir, lamentarse,  deplorar, pesar, arrepentimiento, remordimiento, pena, lamentación",
"transporte, carruaje, carro, coche, vagón, carroza, cochecito, porte, calesa, carreta",
"sabiduría, sabio, prudencia,",
"perdon, perdonar",
"condenar",
"ahorrar, frugalidad, economía,",
"llorar, afligir, duelo",
"rapido, pronto, inmediato",
"dudar, vacilar, titubear, hesitar,  oscilar",
"embajador, embajadora, representante",
"apresuradamente, rápidamente, precipitadamente, a toda prisa",
"engreído, vanidoso, presumido, presuntuoso, arrogante, creído ",
"admirador, admiradora",
"saludo",
"aplaudir",
"lejos",
"aclamacion, reconocimiento, aclamar",
"alabanza, elogio, gloria, halago, reconocimiento, adoración, alabar, elogiar",
"respecto, consierar",
"bebedor, borrachín",
"quien, que, cual, quién, ellos, a quién",
"lugubre",
"así, tan, entonces, por lo que, muy, por lo tanto, mucho, por eso",
"confesar, confesarse, reconocer, admitir",
"traer, llevar, aportar, dar, poner, acercar, hacer, lograr, introducir",
"rompecabezas, puzzle, puzle, acertijo, enigma, crucigrama, misterio, ingenio, desconcertar, intrigar",
"llegada",
"divertir, divertirse",
"tonterías, disparate",
"vertiginoso, mareado",
"bondad, bien, calidad, benevolencia, benigdnidad, dios",
"error, equivocación, equivocar, confundir",
"adición, suma, añadido",
"reuma",
"pan, hogaza, barra, pastel, holgazonear, flojear",
"empresario ",
"brillo, brillantina, diamantina , brillar, relucir",
"inactivo, ocioso , ociosa, inactividad, holgazonear, haraganear",
"establecer, configurar, fijar, poner, ajustar, conjunto, juego, serie, situado",
"preciso, exacto, exacta, correcto",
"sin embargo, no obstante , pero, aún asi, con todo, pese a todo",
"retorta, replica, respuesta, replicar, contestar, retrucar ",
"malhumor",
"malhumor",
"de ceda, ceda",
"cajón, gaveta, cajonera",
"por completo, en total, totalmente, completamente ",
"farola",
"farolero",
"respeto",
"respetuosamente",
"fregona, trapeador, mopa, trapo, estropajo, mata, trapero, lampazo, trapear, fregar, aljofifar, enjugar",
"frente, ceño",
"pañuelo, puñuelito, lienzo",
"cuadrado, cuadriculado, cuadrar",
"apagarlo",
"simplemente, solo, meramente",
"mas lejos",
"despreciar",
"despreciar, desprecio, desdén",
"bendito, bendecido, bienaventurados",
"pantalón, bragas, jadeo, jadear, desear, resollar",
"geografo",
"estado, situación, público, condición, cargo, poderes públicos, estado federal, estatal, afirmar, indicar, decir, declarar",
"erudito, académico, estudioso, escolar, estudiante, investigador",
"señorial, majestuoso, imponente",
"desastre, catástrofe, desgracia",
"tambien lo haría",
"proporcionar, amueblar, suministrar, facilitar, decorar",
"revolver, remover, mezclar, añadir, agitar, incorporar, mover, batir, revuelo, agitación",
"emoción, entusiasmo, excitación",
"afilar, agudizar, mejorar, afinar, perfeccionar, enfocar, aguzar",
"sacapuntas",
"tinta, tintero, entintado, de tinta, entintar, firmar",
"embarazada, expectante, gestante, encinta, ilusionado, expectativa, embarazo",
"que, cual, qué, donde, cuál, cuyo, lo cual, quien, eso",
"anticuado, antiguo",
"efímero, fugaz",
"desaparición, desaparecimiento",
"ligero, leve, pequeño, mínimo, cierto, suave, escaso, desaire, insulto, despreciar, menospreciar",
"bajar, bajarse, posarse, apearse, descender, desembarcar, aterrizar, desmontar, encendido",
  ];
List<int> numeros = [];

   @override
  void didChangeDependencies() {/*Se trata del cambio que se da durante la ejecucion de la pantalla*/
    super.didChangeDependencies();
    // Inicializar las variables principales aquí
    numeros = List<int>.generate(spanishStr.length-1, (index) => index); // Crear un array con números del 0 al 59
    numeros.shuffle(Random());

  }


  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  final con = FlipCardController();
  final con1 = FlipCardController();
  final cong = GestureFlipCardController();
  final cong1 = GestureFlipCardController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("FlipCards"),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListView(
          children: [
            Center(
                child: Card(
                elevation: 20,
                child: Padding(
                  padding: const EdgeInsets.all(10),
                  child: SizedBox(
                    width: MediaQuery.of(context).size.width * 0.5,
                    child: Container(
                      alignment: Alignment.center,
                      child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Text('EJEMPLO(s)'),
                          Text("Q = ${englishStr[numeros[contadorArr]]}", textAlign: TextAlign.center, ),
                        ],
                      )
                    ),
                  ),
                ) 
              ),
              ),
            //////////////////////////////////////////
            FlipCard(
              animationDuration: const Duration(milliseconds: 900),
              rotateSide: RotateSide.right,
              disableSplashEffect: false,
              splashColor: Colors.orange,
              onTapFlipping: false,
              axis: FlipAxis.vertical,
              controller: con,
              frontWidget: Center(
                child: Card(
              elevation: 20,
                child: SizedBox(
                  width: MediaQuery.of(context).size.width * 0.5,
                  height: MediaQuery.of(context).size.height * 0.2,
                  child: Container(
                    alignment: Alignment.center,
                    child: Text("Q = ${englishStr[numeros[contadorArr]]}", textAlign: TextAlign.center, )
                  ),
                ) 
              ),
              ),
              backWidget: Center(
                child: Card(
                elevation: 20,
                child: SizedBox(
                  width: MediaQuery.of(context).size.width * 0.5,
                  height: MediaQuery.of(context).size.height * 0.2,
                  child: Container(
                    alignment: Alignment.center,
                    child: Text("A = ${spanishStr[numeros[contadorArr]]}", textAlign: TextAlign.center, )
                  ),
                ) 
                            ),
              ),
            ),
            const SizedBox(
              height: 20,
            ),
              ElevatedButton(
              child: Text(texto),
              onPressed:  btn ? () async {
              
              switch (contador) {
                case 0:
                  btn = false;
                  setState(() {  });
                  await con.flipcard();
                  // await con1.flipcard();
                  btn = true;
                  texto ='Next';
                  contador++;
                  break;
                case 1:
                  btn = false;
                  if(contadorArr < englishStr.length){
                    contadorArr ++;
                  }else{
                    contadorArr = 0;
                  }
                  setState(() {  });
                  await con.flipcard();
                  await con1.flipcard();
                  btn = true;
                  texto = 'Flip';
                  contador = 0;
                break;
              }
              setState(() {  });
              
              } : null
            )
          ],
        ),
      ),
    );
  }
}
